NEON: implement all intrinsics supported by architecture A64-part1
simd-everywhere/simde pull request #1090
Opened 2023-10-23 03:44 UTC by yyctw

Hi all, this is Eric from Andes Technology Corporation. This PR is part of the [previous PR](https://github.com/simd-everywhere/simde/pull/1080) and includes the following:
Add 368 initial implementations and corresponding test cases in 88 families which are listed below:
- `abd`, `abdl_high`, `add`, `addhn_high`, `bsl`, `ceq`, `ceqz`, `cgez`, `cgtz`, `cle`,
- `cltz`, `cmla`, `cmla_rot180`, `cmla_rot270`, `cmla_rot90`, `cnt`, `copy_lane`, `cvt`, `cvt_n`, `cvtm`,
-  `cvtp`, `dot`, `dot_lane`, `dup_n`, `eor`, `fms_n`, `ld1`, `ld3`, `ld4`, `maxnm`,
-  `maxv`, `minnm`, `minv`, `mull`, `mull_high`, `mvn`, `pmin`, `qrdmulh_lane`, `qrshl`, `qrshrn_high_n`,
-  `qrshrun_high_n`, `qshl_n`, `qshlu_n`, `qshrn_high_n`, `qshrn_n`, `qshrun_n`, `qtbl`, `qtbx`, `raddhn`, `raddhn_high`,
-  `rbit`, `reinterpret`, `rev16`, `rev32`, `rev64`, `rnd`, `rndi`, `rndm`, `rndp`, `rshrn_high_n`,
-  `rsubhn`, `rsubhn_high`, `shr_n`, `shrn_n`, `sli_n`, `sri_n`, `st1`, `st1_lane`, `st1_x2`, `st1_x3`,
-  `st1_x4`, `st1q_x2`, `st1q_x3`, `st1q_x4`, `st2_lane`, `st3`, `st3_lane`, `st4`, `st4_lane`, `tbl`,
-  `tbx`, `trn`, `trn1`, `trn2`, `tst`, `uzp`, `uzp1`, `uzp2`

2023-10-23 07:27 UTC, mr-c commented
The build error for "Windows MSVC-Aarch64" reminds me of this note in the `.appveyor.yml`.

https://github.com/simd-everywhere/simde/blob/029d7498974eb43fe98b0341ca1dd269ca70d12c/.appveyor.yml#L99

So maybe try replacing 
https://github.com/simd-everywhere/simde/blob/029d7498974eb43fe98b0341ca1dd269ca70d12c/.github/workflows/ci.yml#L662
with `ninja -C build test`

2023-10-23 07:30 UTC, mr-c requested changes
Quick fix for the native-aliases build failure

2023-10-23 07:30 UTC, mr-c commented on simde/arm/neon/rsubhn_high.h
> +  #define vrsubhn_high_s16(a, b) simde_vrsubhn_high_s16((a), (b))
```suggestion
  #define vrsubhn_high_s16(r, a, b) simde_vrsubhn_high_s16((r), (a), (b))
```

2023-10-23 07:30 UTC, mr-c commented on simde/arm/neon/rsubhn_high.h
> +  #define vrsubhn_high_s32(a, b) simde_vrsubhn_high_s32((a), (b))
```suggestion
  #define vrsubhn_high_s32(r, a, b) simde_vrsubhn_high_s32((r), (a), (b))
```

2023-10-23 07:30 UTC, mr-c commented on simde/arm/neon/rsubhn_high.h
> +  #define vrsubhn_high_s64(a, b) simde_vrsubhn_high_s64((a), (b))
```suggestion
  #define vrsubhn_high_s64(r, a, b) simde_vrsubhn_high_s64((r), (a), (b))
```

2023-10-23 07:30 UTC, mr-c commented on simde/arm/neon/rsubhn_high.h
> +  #define vrsubhn_high_u16(a, b) simde_vrsubhn_high_u16((a), (b))
```suggestion
  #define vrsubhn_high_u16(r, a, b) simde_vrsubhn_high_u16((r), (a), (b))
```

2023-10-23 07:30 UTC, mr-c commented on simde/arm/neon/rsubhn_high.h
> +  #define vrsubhn_high_u32(a, b) simde_vrsubhn_high_u32((a), (b))
```suggestion
  #define vrsubhn_high_u32(r, a, b) simde_vrsubhn_high_u32((r), (a), (b))
```

2023-10-23 07:30 UTC, mr-c commented on simde/arm/neon/rsubhn_high.h
> +  #define vrsubhn_high_u64(a, b) simde_vrsubhn_high_u64((a), (b))
```suggestion
  #define vrsubhn_high_u64(r, a, b) simde_vrsubhn_high_u64((r), (a), (b))
```

2023-10-23 07:42 UTC, yyctw commented
> Quick fix for the native-aliases build failure

It has been fixed.

2023-10-23 08:55 UTC, mr-c requested changes
Initial review of the 1st 50 files; I'll review the next batch when these comments are resolved.

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/add.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

Not yet, I don't think

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/bsl.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/ceq.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
*   2020      Evan Nemerson <evan@nemerson.com>
```
Evan wrote the first version of this file..

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/ceqz.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cmla.h
> +*   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cmla_rot180.h
> +*   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cmla_rot270.h
> +*   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cmla_rot90.h
> +*   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cnt.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
 *   2020      Evan Nemerson <evan@nemerson.com>
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +        simde_float16_to_float32(a));
There should be test cases added to `test_simde_vcvth_s16_f16` that show the different behavior if `SIMDE_FAST_CONVERSION_RANGE` is defined, or not.

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
>        return INT16_MAX;
Likewise, there should be test cases in `test_simde_vcvth_s16_f16` that trigger these code paths involving `INT16_{MIN,MAX}`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Same comments as for `simde_vcvth_s16_f16`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
>        return 0;
And a test case involving a NAN; probably better to test with `simde_math_isnanhf(a)` as we might get an optimized implementation someday

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
>        return 0;
Same comments as for `simde_vcvth_s16_f16`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Same comments as for `simde_vcvth_s16_f16`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Same comments as for `simde_vcvth_s16_f16`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Same comments as for `simde_vcvth_s16_f16`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    if (HEDLEY_UNLIKELY(af <= HEDLEY_STATIC_CAST(simde_float32, 0.0))) {
```suggestion
    if (HEDLEY_UNLIKELY(af <= SIMDE_FLOAT32_C(0.0))) {
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    if (HEDLEY_UNLIKELY(af <= HEDLEY_STATIC_CAST(simde_float32, 0.0))) {
```suggestion
    if (HEDLEY_UNLIKELY(af <= SIMDE_FLOAT32_C(0.0))) {
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    if (HEDLEY_UNLIKELY(af < HEDLEY_STATIC_CAST(simde_float32, 0.0))) {
```suggestion
    if (HEDLEY_UNLIKELY(af < SIMDE_FLOAT32_C(0.0))) {
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    if (HEDLEY_UNLIKELY(af < HEDLEY_STATIC_CAST(simde_float32, 0.0))) {
```suggestion
    if (HEDLEY_UNLIKELY(af < SIMDE_FLOAT32_C(0.0))) {
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    if (HEDLEY_UNLIKELY(af < HEDLEY_STATIC_CAST(simde_float32, 0.0))) {
```suggestion
    if (HEDLEY_UNLIKELY(af < SIMDE_FLOAT32_C(0.0))) {
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +      return 0;
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    return HEDLEY_STATIC_CAST(int32_t, simde_math_roundf(a));
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvt.h
> +    return HEDLEY_STATIC_CAST(uint32_t, simde_math_roundf(a));
Needs test coverage

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvtm.h
same comments as `cvt.h`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/cvtp.h
same comments as `cvt.h`

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/dot.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/dot_lane.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/dup_n.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/eor.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/ld1.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/maxnm.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/maxv.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/minnm.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/minv.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/mull.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/mull_high.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/mvn.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/pmin.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/qrdmulh_lane.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/qrshl.h
> +/* Notes from the implementer (Christopher Moore aka rosbif)
Does this note still make sense here?

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/qshlu_n.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/qshrun_n.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/qtbl.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 08:55 UTC, mr-c commented on simde/arm/neon/qtbx.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 15:43 UTC, yyctw commented
> Initial review of the 1st 50 files; I'll review the next batch when these comments are resolved.

@mr-c I have addressed all the comments. My apologies for inadvertently deleting and adding the Copyright. Thank you for your review!

2023-10-23 15:44 UTC, mr-c commented on simde/arm/neon/qrshl.h
> +/* Notes from the implementer (Christopher Moore aka rosbif)
Maybe better to refer to the original file instead of duplicating the comment

2023-10-23 16:14 UTC, mr-c requested changes
1st 75 files reviewed. Some errant copyright statements still.

Thank you for including the test generation code!

2023-10-23 16:14 UTC, mr-c commented on simde/arm/neon/sri_n.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-23 16:14 UTC, mr-c commented on simde/arm/neon/st1_x2.h
> - *   2021      Décio Luiz Gazzoni Filho <decio@decpp.net>
These shouldn't be deleted

2023-10-23 16:14 UTC, mr-c commented on simde/arm/neon/st1_x3.h
> - *   2021      Décio Luiz Gazzoni Filho <decio@decpp.net>
.

2023-10-23 16:14 UTC, mr-c commented on simde/arm/neon/st1_x4.h
> - *   2021      Décio Luiz Gazzoni Filho <decio@decpp.net>
.

2023-10-23 16:14 UTC, mr-c commented on simde/arm/neon/st1q_x4.h
> - *   2021      Décio Luiz Gazzoni Filho <decio@decpp.net>
.

2023-10-23 16:14 UTC, mr-c commented on simde/arm/neon/tbl.h
> + *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
```suggestion
```

2023-10-24 01:26 UTC, yyctw commented
> 1st 75 files reviewed. Some errant copyright statements still.
> 
> Thank you for including the test generation code!

Already fixed.

2023-10-24 10:12 UTC, mr-c approved these changes
LGTM!

2023-10-24 10:21 UTC, merged