Fix qdmlal instructions
simd-everywhere/simde pull request #1194
Opened 2024-07-15 16:36 UTC by Ryo-not-rio

qdmlal instructions were implemented without saturation. This has been fixed by utilising existing SIMDe saturating mult and add instructions. Unit tests have been updated to test for all possible saturation cases.

- Fix qdmlal, qdmlal_n, qdmlal_lane,  qdmlal_high, qdmlal_high_n and qdmlal_high_lane
- Update unit tests for qdmlal, qdmlal_n, qdmlal_lane, qdmlal_high, qdmlal_high_n, qdmala_high_lane

2024-07-15 16:39 UTC, mr-c commented
Thank you @Ryo-not-rio ! Based upon who your employer is, I presume your test cases were verified on real hardware, not QEMU?

2024-07-16 08:12 UTC, Ryo-not-rio commented
> Thank you @Ryo-not-rio ! Based upon who your employer is, I presume your test cases were verified on real hardware, not QEMU?

Yes, they have been tested on real hardware :)

2024-08-20 09:55 UTC, mr-c requested changes
Please fix the test failures, thanks!

2025-01-04 03:08 UTC, mr-c approved these changes
Thank you @Ryo-not-rio !

2025-01-04 08:50 UTC, merged