arm: Rename internal ARM ROL/ROR/LSR/LSL functions with a SIMDE prefix.
simd-everywhere/simde pull request #1252
Opened 2024-12-31 22:39 UTC by Syonyk

Most SIMDe functions/macros/etc have the SIMDE_ or simde_ prefix internally. Several of the ARM hash functions do not have this prefix on their ROR/ROL/LSR/LSL macros, and this means that the standard names of can conflict with other projects using the library.  This was an issue on an internal tool using the library, and while SIMDe undefines the macros after the file uses them, this is not compatible with other declarations of these macros before the SIMDe library is included.

This is purely a cosmetic change with internal function renaming.  It changes no external interfaces, simply removes a source of potential conflict with other projects that have similarly named macros.  Tests have not been changed, as there are no changes that would require test modification.

2025-01-01 05:04 UTC, mr-c approved these changes

2025-01-02 19:52 UTC, mr-c requested changes
@Syonyk Can you look at https://github.com/simd-everywhere/simde/actions/runs/12564616889/job/35027928010?pr=1252#step:8:2991 ?

```
../test/arm/neon/../../../simde/arm/neon/sm3.h: In function ‘test_simde_vsm3tt1aq_u32’:
../test/arm/neon/../../../simde/arm/neon/sm3.h:70:7: error: ‘r_.values’ may be used uninitialized [-Werror=maybe-uninitialized]
   70 |       r_,
```

2025-01-02 20:05 UTC, Syonyk commented
Yeah, I'll take a look at that - not sure why my changes would have impacted that, but it shouldn't be a hard fix.

2025-01-02 20:11 UTC, mr-c commented
> Yeah, I'll take a look at that -

Thank you!

> not sure why my changes would have impacted that

Welcome to the wonderful world of testing with many different compilers & configurations :sob: :smiley:

2025-01-02 20:14 UTC, Syonyk commented
Possible fix for it pushed, I don't see r_ being used uninitialized, but I've set it to zero on creation.  Now to see if the tests all pass...

2025-01-02 21:56 UTC, mr-c commented
> Possible fix for it pushed, I don't see r_ being used uninitialized, but I've set it to zero on creation. Now to see if the tests all pass...

https://github.com/simd-everywhere/simde/actions/runs/12588180130/job/35085567566?pr=1252#step:8:3001

Maybe better to use `SIMDE_DIAGNOSTIC_DISABLE_UNINITIALIZED_` in the tests or in `simde/arm/neon/sm3.h` 

If you want the experience, you could also file a bug with the GCC people, letting them know of this spurious warning in gcc-14 using the riscv64 target and `-03`

2025-01-02 22:14 UTC, Syonyk commented
I see that... let me try your approach.  I'll gate it on RISCV for now, and see if that makes things happy.

2025-01-02 22:50 UTC, Syonyk commented
Does this pass at head?  I don't know how to kick off a set of tests against current master.

2025-01-02 22:52 UTC, mr-c commented
> Does this pass at head? I don't know how to kick off a set of tests against current master.

I'm going to debug locally and I'll force push any needed changes; thank you!

2025-01-02 23:39 UTC, mr-c approved these changes

2025-01-03 05:38 UTC, merged